services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
