name: CI/CD Pipeline - Build, Scan & Push to ECR

on:
  push:
    branches: ["main", "devops-setup"]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-1
  ECR_BACKEND: 374196135459.dkr.ecr.ap-southeast-1.amazonaws.com/prompt-engineer-agent-backend
  ECR_FRONTEND: 374196135459.dkr.ecr.ap-southeast-1.amazonaws.com/prompt-engineer-agent-frontend

jobs:
  backend-ci:
    name: Build & Push Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ECR_BACKEND }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Build and Push Docker Image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.ECR_BACKEND }}:${{ github.sha }}
            ${{ env.ECR_BACKEND }}:latest

  frontend-ci:
    name: Build & Push Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ECR_FRONTEND }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Build and Push Docker Image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/frontend
          file: ./frontend/frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.ECR_FRONTEND }}:${{ github.sha }}
            ${{ env.ECR_FRONTEND }}:latest
